import { NextRequest, NextResponse } from 'next/server';
import { store } from '@/lib/supabase/data-store';
import { generateQuotationPdf } from '@/lib/pdf/generator';
import { getAuthenticatedUserContext } from '@/lib/supabase/auth-context';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const token = searchParams.get('token');
    const quoteId = searchParams.get('id');

    const sample = searchParams.get('sample');

    if (sample === 'true' || sample === 'quote' || sample === '1') {
      const sampleQuote: any = {
        id: 'sample-quotation-specimen',
        quotation_number: 'SAMPLE-000042',
        status: 'APPROVED',
        issue_date: new Date().toISOString(),
        valid_until: new Date(Date.now() + 30 * 86400000).toISOString(),
        subtotal: 8900,
        tax_amount: 1602,
        total_amount: 10502,
        currency: 'USD',
        notes: 'This is a demonstration specimen PDF generated by QuoteFlow SaaS.',
        terms: '1. Standard commercial sample terms.\n2. Specimen watermark preview.',
        customer: {
          name: 'CyberShield Networks Inc. (Sample)',
          email: 'sample.client@example.com',
          phone: '+1 206 555 0192',
          address_line1: '100 Innovation Way, Suite 400',
          city: 'Seattle',
          state: 'WA',
          country: 'United States',
          postal_code: '98101',
        },
        organization: {
          name: 'QuoteFlow Technologies (Specimen)',
          email: 'sales@quoteflow.app',
          phone: '+91 98765 43210',
          address_line1: 'Tech Innovation Park',
          city: 'Bengaluru',
          state: 'Karnataka',
          country: 'India',
          postal_code: '560038',
          gst_vat_number: '29ABCDE1234F1Z5',
          brand_color: '#4f46e5',
          invoice_footer: 'Thank you for choosing QuoteFlow — Professional Estimation & Invoicing.',
        },
        items: [
          {
            id: 'item-1',
            description: 'Managed Cloud Security & Zero-Trust Architecture (Sample)',
            quantity: 1,
            unit_price: 6400,
            tax_rate: 18,
            tax_amount: 1152,
            total: 7552,
          },
          {
            id: 'item-2',
            description: 'Automated Continuous Compliance Monitoring (Sample)',
            quantity: 1,
            unit_price: 2500,
            tax_rate: 18,
            tax_amount: 450,
            total: 2950,
          },
        ],
      };

      const pdfBytes = await generateQuotationPdf(sampleQuote);
      return new NextResponse(Buffer.from(pdfBytes), {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'inline; filename="Sample-Quotation-Specimen.pdf"',
          'Cache-Control': 'public, max-age=3600',
        },
      });
    }

    if (sample === 'invoice') {
      const { generateInvoicePdf } = await import('@/lib/pdf/invoice-pdf-generator');
      const sampleInvoice: any = {
        id: 'sample-invoice-specimen',
        invoice_number: 'SAMPLE-INV-000018',
        status: 'PAID',
        issue_date: new Date().toISOString(),
        due_date: new Date(Date.now() + 15 * 86400000).toISOString(),
        subtotal: 8900,
        tax_amount: 1602,
        total_amount: 10502,
        currency: 'USD',
        notes: 'Commercial specimen invoice for demonstration only.',
        payment_terms: 'Payment Received in Full.',
        customer: {
          name: 'CyberShield Networks Inc. (Sample)',
          email: 'sample.client@example.com',
          phone: '+1 206 555 0192',
          address_line1: '100 Innovation Way, Suite 400',
          city: 'Seattle',
          state: 'WA',
          country: 'United States',
          postal_code: '98101',
        },
        organization: {
          name: 'QuoteFlow Technologies (Specimen)',
          email: 'invoicing@quoteflow.app',
          phone: '+91 98765 43210',
          address_line1: 'Tech Innovation Park',
          city: 'Bengaluru',
          state: 'Karnataka',
          country: 'India',
          postal_code: '560038',
          gst_vat_number: '29ABCDE1234F1Z5',
          brand_color: '#4f46e5',
          invoice_footer: 'Official commercial sample invoice — QuoteFlow SaaS.',
        },
        items: [
          {
            id: 'item-1',
            description: 'Managed Cloud Security & Zero-Trust Architecture (Sample)',
            quantity: 1,
            unit_price: 6400,
            tax_rate: 18,
            tax_amount: 1152,
            total: 7552,
          },
          {
            id: 'item-2',
            description: 'Automated Continuous Compliance Monitoring (Sample)',
            quantity: 1,
            unit_price: 2500,
            tax_rate: 18,
            tax_amount: 450,
            total: 2950,
          },
        ],
      };

      const pdfBytes = await generateInvoicePdf(sampleInvoice);
      return new NextResponse(Buffer.from(pdfBytes), {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'inline; filename="Sample-Tax-Invoice-Specimen.pdf"',
          'Cache-Control': 'public, max-age=3600',
        },
      });
    }

    let quote = null;
    if (token) {
      quote = await store.getQuotationByPublicToken(token);
    }
    if (!quote && quoteId) {
      quote = await store.getQuotationById(quoteId);
    }

    if (!quote) {
      return NextResponse.json({ error: 'Quotation not found' }, { status: 404 });
    }

    if (!token && quoteId) {
      const auth = await getAuthenticatedUserContext();
      if (auth) {
        if (quote.organization_id && auth.orgId && quote.organization_id !== auth.orgId) {
          return NextResponse.json({ error: 'Quotation not found' }, { status: 404 });
        }
      }
    }

    const pdfBytes = await generateQuotationPdf(quote);

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="Quotation-${quote.quotation_number}.pdf"`,
        'Cache-Control': 'no-cache',
      },
    });
  } catch (err: any) {
    console.error('PDF generation error:', err);
    return NextResponse.json(
      { error: err.message || 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
